#!/bin/bash

RES=2000

declare -a COLOR
declare -A MASK
declare -A SUBSTRATE
declare -A SILK

COLOR=("red" "green" "blue" "black" "purple")
MASK[red]='#CC0000'
MASK[green]='#00AA00'
MASK[blue]='#0066CC'
MASK[black]='#222222'
MASK[purple]='#4b0082'

SUBSTRATE[red]='#660000'
SUBSTRATE[green]='#004400'
SUBSTRATE[blue]='#002266'
SUBSTRATE[black]='#000000'
SUBSTRATE[purple]='#290060'

SILK[red]="white"
SILK[green]="white"
SILK[blue]="white"
SILK[black]="white"
SILK[purple]="white"

declare -a FINISH
declare -A FINISH_COLOR

FINISH=(hasl enig)
FINISH_COLOR[hasl]="#888888"
FINISH_COLOR[enig]="#DDB500"

function makeimg() {
    local BASE=$1
    local LAYER=$2
    local FG=$3
    local BG=$4
    echo "Generating $BASE $LAYER"
    gerbv --border=0 --dpi=$RES --export=png "$BASE.outline.gbr" "$BASE.$LAYER.gbr" --output="$BASE.$LAYER.png" --foreground='#000000' --foreground="$FG" --background="$BG"
}

function color() {
    local FILE=$1
    local OLD=$2
    local NEW=$3
    convert "$FILE" -fuzz "20%" -fill "$NEW" -opaque "$OLD" ".$FILE"
    mv ".$FILE" "$FILE"
}

function transparent() {
    local FILE=$1
    local BG=$2
    convert "$FILE" -fuzz "10%" -transparent "$BG" ".$FILE"
    mv ".$FILE" "$FILE"
}

function maketexture() {
    local FILE=$1
    local SIDE=$2
    local METAL=$3
    local MASK=$4
    local SHADOW=$5
    local OUT=$6

    convert -background transparent "$FILE.$SIDE.png" -compose overlay "$FILE.${SIDE}mask.png" -flatten "$OUT"
    color "$OUT" "#888888" "$MASK"
    color "$OUT" "black" "$SHADOW"
    color "$OUT" "white" "$METAL"
    convert -background transparent "$OUT" -compose screen "$FILE.${SIDE}silk.png" -flatten ".$OUT"
    mv ".$OUT" "$OUT"
}

function makemirror() {
    local FILE=$1
    local SIDE=$2
    local OUT=$3

    convert -background transparent "$FILE.$SIDE.png" -compose overlay "$FILE.${SIDE}mask.png" -flatten "$OUT"
    color "$OUT" "white" "white"
    color "$OUT" "#888888" "black"
    color "$OUT" "black" "black"
}

function fliptexture() {
    local FILE=$1
    convert "$FILE" -flip "$FILE"
}

B=$1

if [ -z "$B" ]; then
    echo "Usage: $0 <Base>";
    exit 10
fi

makeimg "$B" "top" "#FFFFFF" "#000000"
makeimg "$B" "bottom" "#FFFFFF" "#000000"
makeimg "$B" "topsilk" "#FFFFFF" "#000000"
color "$B.topsilk.png" "#aaaaaa" "#FFFFFF"
transparent "$B.topsilk.png" "black"
makeimg "$B" "bottomsilk" "#FFFFFF" "#000000"
color "$B.bottomsilk.png" "#aaaaaa" "#FFFFFF"
transparent "$B.bottomsilk.png" "black"

makeimg "$B" "topmask" "#FFFFFF" "#000000"
makeimg "$B" "bottommask" "#FFFFFF" "#000000"

makemirror "$B" "top" "$B.topmirror.png"
makemirror "$B" "bottom" "$B.bottommirror.png"

echo "Creating textures..."
for F in ${FINISH[@]}; do
    for C in ${COLOR[@]}; do
        echo -n "   $C $F..."
        maketexture "$B" "top" "${FINISH_COLOR[$F]}" "${MASK[$C]}" "${SUBSTRATE[$C]}" "$B.top-$C-$F.png"
        maketexture "$B" "bottom" "${FINISH_COLOR[$F]}" "${MASK[$C]}" "${SUBSTRATE[$C]}" "$B.bottom-$C-$F.png"
        fliptexture "$B.bottom-$C-$F.png"
        echo "done"
    done
done

# And calculate bump maps
echo "Making bump maps"
convert -background black "$B.top.png" "$B.topsilk.png" -flatten "$B.topbump.png"
convert -background black "$B.bottom.png" "$B.bottomsilk.png" -flatten "$B.bottombump.png"
fliptexture "$B.bottombump.png"
fliptexture "$B.bottommirror.png"
fliptexture "$B.bottommask.png"

echo "Generating board shape"
gerbv --border=0 --dpi=$RES --export=svg "$B.outline.gbr" --output="$B.outline.svg" --foreground='#CC0000' --background='#000000'
